travis:
  secure:
    BINSTAR_TOKEN: fxHA31MH0sjxMLCrI1Y/LrvyE+ZDq9htzvq6UlTnjO+1g+jZBsH/5Lre2/XiMrRu1OUDHQ99ILhzeE7NnYTx0FuiDhMzv8G8XwZhnNuBtFL0tg57YPa57NZczbs5uqZFKddadCKIlBSQMsqeuJ54ORVutogtEgs38t6uKETU03AvvdF7m8deDN+wPN99PrlrzXQcD4aWkxd8jEug5qwinIP1+ol9nSWdkFBxseVo8MZrukjsgcNU4rCXFX3bMO5SJkckytyoiQdUIXqqFX7j5akx5Lp2eyu21+GfRHYmuM69HnodZa82z3tdYhlaKAZHX7/ilNgWe8bpceBhK/8p6qxAxrjPwLRBUjXnxsMhrsqLM+jiijxZjAxokYKBwkuYGWiZz6Ivnz3Kcxg9SPfDZvIOOkIfepomcEofgjzkEsfcz+GGHVRmDxq30peXxpkhhAmgtTNXvcAAE6t17BTHbhuvyU88IOxfCIG5gz7F7DaTXO0rnJeqmKZLCh2kvz7Ri8PHj6v/cE4YUez16WxCmfBGPaMWv8OEb3sZpN8UoEu629TrjCGn8+iWFlhFw1XHFL/9imOi8qf+uo4aRhFwf4yZxgAHcEfK8VRQ0qYSfYwcUPn2riy51rX6QlxHS2CDfSt1rMqRWI5Rg2tM3UCUZuLtnMkAQNh3R7MFi4Dw5sQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
