travis:
  secure:
    BINSTAR_TOKEN: uYlKuUf2mvrMsO3jAezrOPJVrVft3ak0jJ3JPgPRBh1vXXoBeAp6hlnTE97v9Hli997D1hGaSZSWlkHdZ0Q4pLbjO22U6oiScXmbEWHNxDKM4y5Q25AeNvWM+UBqD7b55M00r+c7yzzgrwwHIuCKq+vjVwdXhzBhcDze38Wy+2R70qaaWElnHFDpTeTW6Tyrxzdo5l8m4OUy3DxL3tRjo3CoryXQsBz7iKNG63FPa/JbMjeAiBmujcXWoZ7KAulDT3JsayMUzbuQ9ofEjjRiofAgMyT7kJMc8C6gFQTlHa+7tMejNtYiBcfsDW0OaXPYiKZ1jSTTRnBBU34FBrFAG+o3O1fmw2V+ynIcXkFWiq9k7aNpTpT79nYlyhl2W7Mwe+Z2ZxsJ49ROcgOPIb4BXOId8LTxjbVWxxncxwKi7qtjxufl0EKRBVPkivzKDJlERMIUtcCQ8MDo/CbvrrGL1jGTnQZ9DAN3BlUvze60NaSu5EAe9ryi1Xquvf0bmtOSScjZE7KcOSfUN6cN9N+rLNv7BV3qcuv72nqeYKyREUj/ZaAacPAyy2UhXNJZqJT6IDt+Nz9gaHjWCg/aRwh+Afd4kVzvvLqAeEcnF59LeM+oprWYjatbT17QIIHEQlvJSvB9u5L/bLaTaumzMqR+Itd3ENG+c6f3xsmskPPeR3g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
